feature/amplify-auth
motib8tas/zaseki pull request #25
Opened 2023-04-13 08:29 UTC by zygo-sem

2023-04-14 16:05 UTC, tomoyaki requested changes
@zygo-sem 
巨大PRありがとうございます！！！めっっちゃ進化して嬉しいです（特にログイン周り、完璧）！！
SeatList.vueで、細かいですが修正してほしいところがあるのでチェックしてほしいです。

2023-04-14 16:05 UTC, tomoyaki commented on src/components/SeatList.vue
> +        console.log("seats: ", this.seats);
ここの実装、ちょっと考えたい。
着席フラグでよいのか、ログインユーザが座っている座席IDを持たせる必要がないか？を気にしています。（前にSlackに投下した実装検討したとき＊は、座席IDを持たせようとしていた。）
＊：https://untitled-geh5982.slack.com/archives/C0473MGJCMD/p1680534094917739

2023-04-18 05:30 UTC, zygo-sem commented on src/views/LoginView.vue
> +}
消し忘れてました…

2023-04-18 05:33 UTC, zygo-sem commented on src/components/SeatList.vue
> +        console.log("seats: ", this.seats);
①オブジェクトにログインしているユーザのemployeeIdと同じemployeeIdが存在するか確認
②存在していたら、その座席IDを持ってくる

だと思うんだけど、②の方法がぱっと思い浮かばないので、Issue切って、いったんpushします。

2023-04-18 09:01 UTC, tomoyaki commented on src/components/SeatList.vue
> +        console.log("seats: ", this.seats);
了解す！

2023-04-18 10:38 UTC, zygo-sem commented
@tomoyaki 
対応しました。RVお願いします。

2023-04-19 06:26 UTC, tomoyaki approved these changes
お疲れ様でした！OKです！

2023-04-19 06:26 UTC, tomoyaki commented
@zygo-sem 
お疲れ様！マージします！！

2023-04-19 06:27 UTC, merged